version: 2

build:
  os: ubuntu-24.04
  tools:
    python: "3.12"
  apt_packages:
    - meson 
    - ninja-build 
    - libgtk-4-dev 
    - git 
    - gobject-introspection
    - valac 
    - libpulse-dev
    - gir1.2-nm-1.0 
    - gir1.2-gstreamer-1.0
    - libgirepository1.0-dev 
    - gcc 
    - libcairo2-dev
    - pkg-config 
    - python3-dev 
    - gir1.2-gtk-4.0
  
  jobs:
    pre_build:
      - chmod +x docs/build_ignis.sh
      - docs/build_ignis.sh

python:
  install:
    - requirements: docs/requirements.txt
    - requirements: requirements.txt

sphinx:
  configuration: docs/conf.py