name: Question
description: I'd like to ask a question
labels: ["question"]
body:
  - type: markdown
    attributes:
      value: |
        Before opening a new issue, take a moment to search through the current open ones.

        ---

  - type: textarea
    id: desc
    attributes:
      label: Question
      description: "Describe your question"
    validations:
      required: true
