name: Build and Deploy Documentation

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-24.04

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y meson ninja-build libgtk-4-dev git gobject-introspection \
        valac libpulse-dev gir1.2-nm-1.0 gir1.2-gstreamer-1.0 \
        libgirepository1.0-dev gcc libcairo2-dev pkg-config python3-dev gir1.2-gtk-4.0
        
    - name: Install Python dependencies
      run: |
        pip install sphinx pydata-sphinx-theme
        pip install --upgrade -r requirements.txt

    - name: Build gtk4-layer-shell
      run: |
        git clone https://github.com/wmww/gtk4-layer-shell.git
        cd gtk4-layer-shell
        meson setup build --prefix=/usr
        ninja -C build
        sudo ninja -C build install

    - name: Install Ignis
      run: |
        meson setup build --prefix=/usr --libdir "lib/ignis"
        meson compile -C build
        sudo meson install -C build

    - name: Build documentation
      run: |
        cd docs
        make html

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v4
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: docs/_build/html
