name: docs

on:
  push:
    branches:
      - main
    paths:
      - "ignis/**"
      - "docs/**"
  workflow_dispatch:

jobs:
  build:
    uses: ./.github/workflows/build_docs.yaml
    with:
      TAG: "latest"
      DEST_DIR: "latest"