on: [push, pull_request]

name: Linter Analysis
jobs:
  ruff-check:
    name: Ruff
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install ruff

      - name: Check code
        run:
          ruff check ignis/

      - name: Check format
        continue-on-error: true
        run: ruff format ignis/ --check