on: [push, pull_request]

name: Static Analysis
jobs:
  mypy-check:
    name: Mypy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r dev.txt

      - name: Run mypy analysis
        run: |
          mypy
