name: Build Release Documentation

on:
  release:
    types: [published]

jobs:
  build:
    uses: ./.github/workflows/build_docs.yaml
    with:
      TAG: ${{ github.ref_name }}
      DEST_DIR: ${{ github.ref_name }}
