name: Build Stable Documentation

on:

  push:
    branches:
      - stable
    paths:
      - "ignis/**"
      - "docs/**"
  workflow_dispatch:

jobs:
  build:
    uses: ./.github/workflows/build_docs.yaml
    with:
      TAG: ${{ github.event.release.tag_name }}