name: Build Stable Documentation

on:

  push:
    branches:
      - stable
    paths:
      - "ignis/**"
      - "docs/**"

jobs:
  build:
    uses: ./.github/workflows/build_docs.yaml
    with:
      TAG: "v0.2"
      DEST_DIR: "stable"